#!/bin/bash
# sync-task.sh
# Export current task state to a static file for the AI to read.
# Also detects task type and suggests the appropriate workflow.

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
if [ -z "$REPO_ROOT" ] || [ "$REPO_ROOT" = "/" ]; then
    echo "[ERROR] Cannot determine repository root" >&2
    exit 1
fi
TASK_FILE="$REPO_ROOT/.agent/memory/current-task.md"
ACTIVE_SESSION="$REPO_ROOT/.agent/memory/active-session.md"

echo "[sync-task] Exporting current task tracker state to memory..."
if command -v bd &> /dev/null; then
    # Prepend read-only mirror warning header
    {
        echo "# AUTO-GENERATED by sync-task.sh — DO NOT EDIT MANUALLY"
        echo "# This is a read-only mirror of the Beads task graph. Edit tasks via 'bd' commands."
        echo ""
        bd list
    } > "$TASK_FILE"
    echo "[sync-task] Task state exported to $TASK_FILE"

    # Detect task type from Beads output - scan first 5 non-empty lines
    # (head -1 is always the table header, skip it)
    TASK_CONTENT=$(tail -n +2 "$TASK_FILE" 2>/dev/null | head -5 2>/dev/null | tr -s '[:space:]' ' ')
    if echo "$TASK_CONTENT" | grep -qiE 'fix|bug|issue|error|crash'; then
        echo "[sync-task] [BUG] Bug fix detected - suggesting Bug-Fix Workflow"
    elif echo "$TASK_CONTENT" | grep -qiE 'refactor|rewrite|migrate|rename'; then
        echo "[sync-task] [REFACTOR] Refactor detected - suggesting Code Review Workflow"
    elif echo "$TASK_CONTENT" | grep -qiE 'feature|build|create|add|implement'; then
        echo "[sync-task] [FEATURE] Feature detected - suggesting Unified Workflow (9 steps)"
    fi
else
    # Fallback: Preserve existing manual entries or initialize if missing/empty
    if [ ! -f "$TASK_FILE" ] || [ ! -s "$TASK_FILE" ]; then
        cat << 'EOF' > "$TASK_FILE"
# Task: Short title

- Status: ready
- Priority: medium
- Owner: AI agent
- Related files:
- Goal:
- Steps:
    - [ ] Step 1
- Verification:
- Notes:
EOF
        echo "[sync-task] Initialized structured task in $TASK_FILE"
    else
        echo "[sync-task] Beads (bd) not installed. Keeping existing manual task entries."
    fi
fi

# Update active-session.md with current task info if it exists
if [ -f "$ACTIVE_SESSION" ]; then
    TASK_INFO=$(head -3 "$TASK_FILE" 2>/dev/null || echo "No task info")
    # Remove old Current Step section using portable approach
    # Stop at next H2 heading (any letter after ## )
    TMPFILE="${ACTIVE_SESSION}.tmp.$$"
    trap 'rm -f "$TMPFILE" 2>/dev/null' EXIT
    awk '/^## Current Step/{found=1; next} /^## [A-Za-z]/{found=0} !found' "$ACTIVE_SESSION" > "$TMPFILE"
    cat << EOF >> "$TMPFILE"
## Current Step
- **Workflow:** Awaiting task analysis
- **Task:** $TASK_INFO
EOF
    mv "$TMPFILE" "$ACTIVE_SESSION" 2>/dev/null || true
fi

# Count ready tasks and suggest Multi-Agent if >= 3
if command -v bd &> /dev/null; then
    READY_COUNT=$(bd ready --json 2>/dev/null | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || \
                  bd ready --json 2>/dev/null | python -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || \
                  bd ready --json 2>/dev/null | grep -c '"id"' || echo "0")
    if [ "$READY_COUNT" -ge 3 ] 2>/dev/null; then
        echo "[sync-task] [INFO] $READY_COUNT tasks ready - consider Multi-Agent Workflow"
    fi
fi

# Fix 5: Suggest specialist templates based on detected stack
if [ -f "package.json" ]; then
    echo "[sync-task] [INFO] Templates available: api-rest, database, ui-analysis"

    # Fix 5b: Scan import statements for framework-specific templates
    # Scan only `.` (which includes src/) - no double-scanning
    FRAMEWORKS_FOUND=""
    if grep -rq '"next"' . --include="*.tsx" --include="*.ts" --include="*.js" --exclude-dir=node_modules --exclude-dir=.git 2>/dev/null; then
        FRAMEWORKS_FOUND="$FRAMEWORKS_FOUND web-frameworks/nextjs"
    fi
    if grep -rq '"react"' . --include="*.tsx" --include="*.ts" --include="*.js" --exclude-dir=node_modules --exclude-dir=.git 2>/dev/null; then
        FRAMEWORKS_FOUND="$FRAMEWORKS_FOUND frontend/react"
    fi
    if grep -rq '"express"' . --include="*.ts" --include="*.js" --exclude-dir=node_modules --exclude-dir=.git 2>/dev/null; then
        FRAMEWORKS_FOUND="$FRAMEWORKS_FOUND api-rest/express"
    fi
    if grep -rq '"@prisma/client"' . --include="*.ts" --include="*.js" --exclude-dir=node_modules --exclude-dir=.git 2>/dev/null; then
        FRAMEWORKS_FOUND="$FRAMEWORKS_FOUND database/prisma"
    fi
    if grep -rq '"jest"' . --include="*.json" --exclude-dir=node_modules --exclude-dir=.git 2>/dev/null; then
        FRAMEWORKS_FOUND="$FRAMEWORKS_FOUND testing/jest"
    fi

    if [ -n "$FRAMEWORKS_FOUND" ]; then
        echo "[sync-task] [INFO] Detected frameworks:$FRAMEWORKS_FOUND"
    fi
elif [ -f "Cargo.toml" ]; then
    echo "[sync-task] [INFO] Templates available: programming-languages/rust, devops-infrastructure"
    if grep -rq "tokio" Cargo.toml 2>/dev/null; then
        echo "[sync-task] [INFO] Detected: tokio async runtime"
    fi
    if grep -rq "actix" Cargo.toml 2>/dev/null; then
        echo "[sync-task] [INFO] Detected: actix-web framework"
    fi
elif [ -f "pyproject.toml" ] || [ -f "requirements.txt" ]; then
    echo "[sync-task] [INFO] Templates available: programming-languages/python, ai-specialists"
    if grep -rq "django" pyproject.toml requirements.txt 2>/dev/null; then
        echo "[sync-task] [INFO] Detected: Django framework"
    fi
    if grep -rq "fastapi" pyproject.toml requirements.txt 2>/dev/null; then
        echo "[sync-task] [INFO] Detected: FastAPI framework"
    fi
elif [ -f "go.mod" ]; then
    echo "[sync-task] [INFO] Templates available: programming-languages/go, devops-infrastructure"
elif [ -f "pom.xml" ] || [ -f "build.gradle" ]; then
    echo "[sync-task] [INFO] Templates available: programming-languages/java, database"
    if grep -rq "spring" . --include="*.java" --include="*.xml" --include="*.gradle" --exclude-dir=node_modules --exclude-dir=.git 2>/dev/null; then
        echo "[sync-task] [INFO] Detected: Spring framework"
    fi
fi

