# sync-task.ps1
# Export current task state to a static file for the AI to read.
# Also detects task type and suggests the appropriate workflow.

# Helper: Check for bd.exe directly, bypassing broken npm wrapper
function Test-BdInstalled {
    $bdExe = Get-Command bd.exe -ErrorAction SilentlyContinue
    if ($bdExe) { return $bdExe.Source }
    # Fallback: check if bd.exe is in PATH without .exe extension
    $bdPlain = Get-Command bd -ErrorAction SilentlyContinue
    if ($bdPlain -and $bdPlain.Source -and $bdPlain.Source -match 'bd\.exe$') {
        return $bdPlain.Source
    }
    return $null
}

$RepoRoot = git rev-parse --show-toplevel 2>$null
if (-not $RepoRoot) { $RepoRoot = (Get-Location).Path }
$TaskPath = "$RepoRoot\.agent\memory\current-task.md"
$ActiveSession = "$RepoRoot\.agent\memory\active-session.md"

$BdPath = Test-BdInstalled
Write-Host "[sync-task] Exporting current task tracker state to memory..."
if ($BdPath) {
    # Try bd.exe - may fail on Windows without CGO (requires server mode)
    $bdOutput = & $BdPath list 2>$null
    if ($LASTEXITCODE -eq 0 -and $bdOutput) {
        # Prepend read-only mirror warning header
        $Header = "# AUTO-GENERATED by sync-task.ps1 — DO NOT EDIT MANually`n# This is a read-only mirror of the Beads task graph. Edit tasks via 'bd' commands.`n`n"
        $Header + $bdOutput | Out-File -FilePath $TaskPath -Encoding utf8
        Write-Host "[sync-task] Task state exported to $TaskPath"
    } else {
        Write-Host "[sync-task] bd available but not initialized (run 'bd init --mode server' on Windows)"
    }

    # Detect task type from Beads output - scan first 5 lines after header
    $TaskOutput = Get-Content $TaskPath -TotalCount 6 -ErrorAction SilentlyContinue | Select-Object -Skip 1 | Out-String
    if ($TaskOutput -match 'fix|bug|issue|error|crash') {
        Write-Host "[sync-task] Bug fix detected - suggesting Bug-Fix Workflow"
    } elseif ($TaskOutput -match 'refactor|rewrite|migrate|rename') {
        Write-Host "[sync-task] Refactor detected - suggesting Code Review Workflow"
    } elseif ($TaskOutput -match 'feature|build|create|add|implement') {
        Write-Host "[sync-task] Feature detected - suggesting Unified Workflow (9 steps)"
    }
} else {
    # Fallback: Preserve existing manual entries or initialize if missing/empty
    if (-not (Test-Path $TaskPath) -or (Get-Item $TaskPath).Length -eq 0) {
        $TaskTemplate = @"
# Task: Short title

- Status: ready
- Priority: medium
- Owner: AI agent
- Related files:
- Goal:
- Steps:
    - [ ] Step 1
- Verification:
- Notes:
"@
        $TaskTemplate | Out-File -FilePath $TaskPath -Encoding utf8
        Write-Host "[sync-task] Initialized structured task in $TaskPath"
    } else {
        Write-Host "[sync-task] Beads (bd) not installed. Keeping existing manual task entries."
    }
}

# Update active-session.md with current task info if it exists
if (Test-Path $ActiveSession) {
    $TaskInfo = Get-Content $TaskPath -First 3 -ErrorAction SilentlyContinue
    if ($TaskInfo) {
        # Remove old Current Step section (non-greedy: stops at next ## header) and append new one
        $Content = Get-Content $ActiveSession -Raw
        if ($Content -match '(?s)## Current Step.*?(?=\n## |\z)') {
            $Content = $Content -replace '(?s)## Current Step.*?(?=\n## |\z)', ''
        }
        $Content += "`n## Current Step`n- **Workflow:** Awaiting task analysis`n- **Task:** $($TaskInfo -join "`n")`n"
        $Content | Out-File -FilePath $ActiveSession -Encoding utf8
    }
}

# Count ready tasks and suggest Multi-Agent if >= 3
if ($BdPath) {
    try {
        $ReadyOutput = & $BdPath ready 2>$null
        if ($ReadyOutput) {
            $ReadyCount = ($ReadyOutput | Measure-Object -Line).Lines
            if ($ReadyCount -ge 3) {
                Write-Host "[sync-task] $ReadyCount tasks ready - consider Multi-Agent Workflow"
            }
        }
    } catch { }
}

# Suggest specialist templates based on detected stack
if (Test-Path "package.json") {
    Write-Host "[sync-task] Templates available: api-rest, database, ui-analysis"

    # Scan import statements for framework-specific templates
    $AllSourceFiles = Get-ChildItem -Path $RepoRoot -Include '*.tsx','*.ts','*.js' -Recurse -ErrorAction SilentlyContinue | Where-Object {
        $full = $_.FullName -replace '\\','/'
        $full -notmatch '/node_modules/' -and $full -notmatch '/\.git/'
    }
    if ($AllSourceFiles | Select-String -Pattern '"next"' -Quiet -ErrorAction SilentlyContinue) {
        Write-Host "[sync-task] Detected: web-frameworks/nextjs"
    }
    if ($AllSourceFiles | Select-String -Pattern '"react"' -Quiet -ErrorAction SilentlyContinue) {
        Write-Host "[sync-task] Detected: frontend/react"
    }
    if ($AllSourceFiles | Select-String -Pattern '"express"' -Quiet -ErrorAction SilentlyContinue) {
        Write-Host "[sync-task] Detected: api-rest/express"
    }
    if ($AllSourceFiles | Select-String -Pattern '"@prisma/client"' -Quiet -ErrorAction SilentlyContinue) {
        Write-Host "[sync-task] Detected: database/prisma"
    }
    $JsonFiles = Get-ChildItem -Path $RepoRoot -Include '*.json' -Recurse -ErrorAction SilentlyContinue | Where-Object {
        $full = $_.FullName -replace '\\','/'
        $full -notmatch '/node_modules/' -and $full -notmatch '/\.git/'
    }
    if ($JsonFiles | Select-String -Pattern '"jest"' -Quiet -ErrorAction SilentlyContinue) {
        Write-Host "[sync-task] Detected: testing/jest"
    }
} elseif (Test-Path "Cargo.toml") {
    Write-Host "[sync-task] Templates available: programming-languages/rust, devops-infrastructure"
    if (Select-String -Pattern 'tokio' -Path (Join-Path $RepoRoot 'Cargo.toml') -Quiet -ErrorAction SilentlyContinue) {
        Write-Host "[sync-task] Detected: tokio async runtime"
    }
    if (Select-String -Pattern 'actix' -Path (Join-Path $RepoRoot 'Cargo.toml') -Quiet -ErrorAction SilentlyContinue) {
        Write-Host "[sync-task] Detected: actix-web framework"
    }
} elseif ((Test-Path "pyproject.toml") -or (Test-Path "requirements.txt")) {
    Write-Host "[sync-task] Templates available: programming-languages/python, ai-specialists"
    $PyFiles = @()
    if (Test-Path (Join-Path $RepoRoot 'pyproject.toml')) { $PyFiles += Join-Path $RepoRoot 'pyproject.toml' }
    if (Test-Path (Join-Path $RepoRoot 'requirements.txt')) { $PyFiles += Join-Path $RepoRoot 'requirements.txt' }
    if (($PyFiles | Select-String -Pattern 'django' -Quiet -ErrorAction SilentlyContinue) -or
        ($PyFiles | Select-String -Pattern 'fastapi' -Quiet -ErrorAction SilentlyContinue)) {
        Write-Host "[sync-task] Detected: web framework (django/fastapi)"
    }
} elseif (Test-Path "go.mod") {
    Write-Host "[sync-task] Templates available: programming-languages/go, devops-infrastructure"
} elseif ((Test-Path "pom.xml") -or (Test-Path "build.gradle")) {
    Write-Host "[sync-task] Templates available: programming-languages/java, database"
}
